name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            server/package-lock.json
            client/package-lock.json

      # BACKEND
      - name: Install Server Dependencies
        working-directory: ./server
        run: npm ci

      - name: Lint Server
        working-directory: ./server
        run: npm run lint

      - name: Unit Test Server (Vitest)
        working-directory: ./server
        run: npm run test

      # FRONTEND
      - name: Install Client Dependencies
        working-directory: ./client
        run: npm ci

      - name: Lint Client
        working-directory: ./client
        run: npm run lint

      - name: Unit Test Client (Vitest)
        working-directory: ./client
        run: npx vitest run --passWithNoTests
